using System;
using System.Collections.Generic;
using System.Text;

namespace DocFmtXML
{
    partial class b01c_form
    {
        public static string[] field_posi = new string[]{
        "STUD_ID"," 7E39999A",
        "CODE"," 1234567-X",
        "YEAR"," 2019/2020",
        "BP"," 2",
        "IP"," 1",
        "IDT"," BIRNP",
        "RAR"," M",
        "AR"," M",
        "GAR"," M",
        "EAR"," M",
        "ZH_S_CODE"," 澳門中學",
        "PRE_S_CODE"," ",
        "S_CODE"," 159",
        "GRADE"," P1",
        "CLASS"," A",
        "C_NO"," 65",
        };
        public static string[] baseinfo_field_posi = new string[]{
        "NAME_C","0.2",
        "NAME_P","0.4",
        "SEX","2.1",
        "B_DATE","1.3",
        "B_PLACE","1.5",
        "ID_TYPE","3.3",
        "ID_NO","3.5",
        "I_PLACE","5.3",
        "I_DATE","6.4",
        "V_DATE","6.5",
        "S6_TYPE","",
        "S6_IDATE", "7.3",
        "S6_VDATE", "7.5",
        "NATION","9.1",
        "ORIGIN","9.2",
        "R_AREA","",
        "RA_DESC","8.4",
        "AREA","",
        "POSTAL_CODE","10.3",
        "ROAD","10.5",
        "ADDRESS","12.3",
        "TEL","12.5",
        "MOBILE","13.5",
        "FATHER","14.2",
        "MOTHER","15.2",
        "F_PROF","14.4",
        "M_PROF","15.4",
        "GUARD","",
        "G_RELATION","16.4",
        "GUARDMOBIL","16.6",
        "LIVE_SAME",""
       };

        public static string[] GU_field_posi = new string[]{
        "G_NAME","0.2",
        "G_RELATION","",
        "G_PROFESSION","0.4",
        "G_AREA","",
        "G_POSTAL_CODE","",
        "G_ROAD","1.4",
        "G_ADDRESS","3.3",
        "G_TEL","3.5",
        };

        public static string[] EC_field_posi = new string[]{
        "EC_NAME","0.2",
        "EC_REL","0.4",
        "EC_TEL","3.6",
        "EC_AREA","",
        "EC_POSTAL_CODE"," ",
        "EC_ROAD","1.4",
        "EC_ADDRESS","3.3" };
        public static string[] reqinfo_field_posi = new string[]{
        "F_tel1"," 0.1",
        "F_tel2","0.3",
        "M_tel1","1.1",
        "M_tel2","1.3",
        "G_tel1","2.1",
        "G_tel2","2.3",
        "Parent_sms","3.1",
        "STUD_ID","4.1",
        "Stud_sms","5.1" };
        public static string[] reqinfo_other_field_posi = new string[]{
        "Reg_in_date","",
        "Reg_in_Class","",
        "St_status","",
        "Leave_date","",
        "Leave_Class","",
        "Leave_reason","",
        "Religion","",
        "MBC_STUD","",
        "K_CLASS","",
        "K_SCHOOL","",
        "K_EDU","",
        "P_CLASS","",
        "P_SCHOOL","",
        "P_EDU","",
        "S_CLASS","",
        "S_SCHOOL","",
        "S_EDU","",
        "note","",
        "last_class",""
    };
        static string json = @"
[{
        'STUD_ID': '7E39999A',
        'CODE': '1234567-X',
        'YEAR': '2019/2020',
        'BP': '2',
        'IP': '1',
        'IDT': 'BIRNP',
        'RAR': 'M',
        'AR': 'M',
        'GAR': 'M',
        'EAR': 'M',
        'ZH_S_CODE': '澳門中學',
        'PRE_S_CODE': '',
        'NAME_C': '周星星',
        'NAME_P': 'SOU XING XING',
        'SEX': 'M',
        'B_DATE': '2012/01/01',
        'B_PLACE': '',
        'ID_TYPE': '',
        'ID_NO': '1006010(0)',
        'I_PLACE': '',
        'I_DATE': '2019/01/07',
        'V_DATE': '2024/01/07',
        'S6_TYPE': '3=其他逗留許可',
        'S6_IDATE': null,
        'S6_VDATE': null,
        'NATION': '中國',
        'ORIGIN': '廣東',
        'R_AREA': '',
        'RA_DESC': '',
        'AREA': 'M=澳門',
        'POSTAL_CODE': '',
        'ROAD': '大馬路',
        'ADDRESS': '新邨N樓X座',
        'TEL': '/',
        'MOBILE': '61111177',
        'FATHER': '周大福',
        'MOTHER': '秀梅',
        'F_PROF': '律師',
        'M_PROF': '主婦',
        'GUARD': 'M',
        'LIVE_SAME': '0',
        'EC_NAME': '秀梅',
        'EC_REL': '母子',
        'EC_TEL': '61111137',
        'EC_AREA': 'M=澳門',
        'EC_POSTAL_CODE': '',
        'EC_ROAD': '大馬路',
        'EC_ADDRESS': '新邨N樓X座',
        'S_CODE': '159',
        'GRADE': 'P1',
        'CLASS': 'A',
        'C_NO': '65',
        'G_NAME': '秀梅',
        'G_RELATION': '',
        'G_PROFESSION': '主婦',
        'G_AREA': 'M=澳門',
        'G_POSTAL_CODE': '',
        'G_ROAD': '大馬路',
        'G_ADDRESS': '新邨N樓X座',
        'G_TEL': '61111177',
        'GUARDMOBIL': '61111177',
        'F_tel1': '61111197',
        'F_tel2': '/',
        'M_tel1': '61111177',
        'M_tel2': '/',
        'G_tel1': '61111377',
        'G_tel2': '/',
        'Parent_sms': '61111377',
        'Stud_sms': '',
        'Reg_in_date': '2019-09-09',
        'Reg_in_Class': 'P1A',
        'St_status': '3=插班',
        'Leave_date': '',
        'Leave_Class': '',
        'Leave_reason': '',
        'Religion': '',
        'MBC_STUD': '0',
        'K_CLASS': '',
        'K_SCHOOL': '',
        'K_EDU': '',
        'P_CLASS': 'P2',
        'P_SCHOOL': '台東小學',
        'P_EDU': '',
        'S_CLASS': '',
        'S_SCHOOL': '',
        'S_EDU': '',
        'note': '',
        'last_class': ''},
{
        'STUD_ID': '7E39998A',
        'CODE': '1234566-X',
        'YEAR': '2019/2020',
        'BP': '2',
        'IP': '1',
        'IDT': 'BIRNP',
        'RAR': 'M',
        'AR': 'M',
        'GAR': 'M',
        'EAR': 'M',
        'ZH_S_CODE': '澳門中學',
        'PRE_S_CODE': '',
        'NAME_C': '周星星',
        'NAME_P': 'SOU XING XING',
        'SEX': 'M',
        'B_DATE': '2012/01/01',
        'B_PLACE': '',
        'ID_TYPE': '',
        'ID_NO': '1006010(0)',
        'I_PLACE': '',
        'I_DATE': '2019/01/07',
        'V_DATE': '2024/01/07',
        'S6_TYPE': '3=其他逗留許可',
        'S6_IDATE': null,
        'S6_VDATE': null,
        'NATION': '中國',
        'ORIGIN': '廣東',
        'R_AREA': '',
        'RA_DESC': '',
        'AREA': 'M=澳門',
        'POSTAL_CODE': '',
        'ROAD': '大馬路',
        'ADDRESS': '新邨N樓X座',
        'TEL': '/',
        'MOBILE': '61111177',
        'FATHER': '周大福',
        'MOTHER': '秀梅',
        'F_PROF': '律師',
        'M_PROF': '主婦',
        'GUARD': 'M',
        'LIVE_SAME': '0',
        'EC_NAME': '秀梅',
        'EC_REL': '母子',
        'EC_TEL': '61111137',
        'EC_AREA': 'M=澳門',
        'EC_POSTAL_CODE': '',
        'EC_ROAD': '大馬路',
        'EC_ADDRESS': '新邨N樓X座',
        'S_CODE': '159',
        'GRADE': 'P1',
        'CLASS': 'A',
        'C_NO': '65',
        'G_NAME': '秀梅',
        'G_RELATION': '',
        'G_PROFESSION': '主婦',
        'G_AREA': 'M=澳門',
        'G_POSTAL_CODE': '',
        'G_ROAD': '大馬路',
        'G_ADDRESS': '新邨N樓X座',
        'G_TEL': '61111177',
        'GUARDMOBIL': '61111177',
        'F_tel1': '61111197',
        'F_tel2': '/',
        'M_tel1': '61111177',
        'M_tel2': '/',
        'G_tel1': '61111377',
        'G_tel2': '/',
        'Parent_sms': '61111377',
        'Stud_sms': '',
        'Reg_in_date': '2019-09-09',
        'Reg_in_Class': 'P1A',
        'St_status': '3=插班',
        'Leave_date': '',
        'Leave_Class': '',
        'Leave_reason': '',
        'Religion': '',
        'MBC_STUD': '0',
        'K_CLASS': '',
        'K_SCHOOL': '',
        'K_EDU': '',
        'P_CLASS': 'P2',
        'P_SCHOOL': '台東小學',
        'P_EDU': '',
        'S_CLASS': '',
        'S_SCHOOL': '',
        'S_EDU': '',
        'note': '',
        'last_class': ''

    }]
";
}
}
